apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{VM_NAME}}-quota
  namespace: {{NAMESPACE}}

spec:
  hard:
    requests.cpu: "4"
    requests.memory: 2Gi
    persistentvolumeclaims: "5"
    count/virtualmachines.kubevirt.io: "2"

---

apiVersion: v1
kind: LimitRange
metadata:
  name: {{VM_NAME}}-limit-range
  namespace: {{NAMESPACE}}
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container