apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{VM_NAME}}_quota
  namespace: {{NAMESPACE}}

spec:
  hard:
    requests.cpu: "4"
    requests.memory: 2Gi
    persistentvolumeclaims: "5"
    count/virtualmachines.kubevirt.io: "2"